"""Seasonal colour analysis data.

A master colour library (name -> hex) plus fully specified palettes for the
12 classic colour seasons. Every season defines:

  axes         warm / depth / chroma / contrast  (0-100 sliders)
  neutrals     8 wardrobe neutrals
  best         16 recommended shirt colours (Section 4)
  avoid        12 colours to avoid            (Section 5)
  groups       master palette grouped chips   (Section 6)
  metals       recommended / caution / avoid  (Section 9)
  tips         do / don't style tips          (Section 10)
  suit_combos  suit + shirt + tie triples
  casual       casual outfit pairings
  glasses      frame colour recommendations
  hair         hair / beard tone guidance
"""

C = {
    # ---- neutrals / darks ----
    "Navy": "#1F2A44", "Midnight Navy": "#151E33", "Charcoal": "#3A3D42",
    "Soft Charcoal": "#4A4D52", "Black": "#111114", "Soft Black": "#26262B",
    "Espresso": "#3B2A20", "Chocolate": "#4E342E", "Dark Brown": "#3E2C23",
    "Cocoa": "#6B4A38", "Warm Grey": "#8A8178", "Cool Grey": "#9AA0A8",
    "Silver Grey": "#C3C8CE", "Light Grey": "#D4D6D9", "Dove Grey": "#B9BCC1",
    "Stone": "#C8BFB1", "Greige": "#B4AA9B", "Taupe": "#8D8073",
    "Warm Taupe": "#9C8B79", "Mushroom": "#A99E90", "Pewter": "#8E9399",
    # ---- lights ----
    "Pure White": "#FFFFFF", "Ivory": "#F5EFE2", "Cream": "#F1E8D5",
    "Soft White": "#F4F2ED", "Oyster": "#E8E2D4", "Champagne": "#EBDCC3",
    "Ecru": "#E4D9C2", "Porcelain": "#F0EEE9", "Shell": "#F2E9E4",
    # ---- warm earth ----
    "Camel": "#B98F5C", "Tan": "#C6A374", "Caramel": "#A9743C",
    "Cognac": "#8F5A2B", "Rust": "#A9502C", "Terracotta": "#C06442",
    "Burnt Orange": "#B85C2E", "Copper": "#B0653A", "Bronze Brown": "#7C5A34",
    "Mustard": "#C79A2E", "Ochre": "#B98A24", "Golden Yellow": "#D9A62E",
    "Honey": "#C9973F", "Amber": "#C97F26", "Saffron": "#E0952B",
    "Butterscotch": "#D0A15A", "Khaki": "#8F855F", "Sand": "#D6C29A",
    "Pumpkin": "#C46A21", "Apricot": "#E8A66B", "Peach": "#F2B58F",
    "Warm Coral": "#E67A5A", "Salmon": "#EE8B72", "Coral": "#E96A50",
    # ---- greens ----
    "Olive": "#6B6B3A", "Dark Olive": "#4F5230", "Moss": "#707A45",
    "Forest Green": "#2E4A34", "Deep Forest": "#22392A", "Hunter Green": "#2F4A3B",
    "Pine": "#2A4438", "Sage": "#A3AC8F", "Soft Sage": "#B4BBA2",
    "Emerald": "#1E7A56", "Kelly Green": "#2E9E52", "Apple Green": "#7DB74A",
    "Lime": "#B7D34A", "Bright Lime": "#B9E23A", "Neon Green": "#5CF05C",
    "Jade": "#3E8E76", "Seafoam": "#A9D6C4", "Mint": "#B8E4CF",
    "Grass Green": "#4E9A3C", "Spruce": "#2F5148",
    # ---- blues / teals ----
    "Deep Teal": "#175E5E", "Petrol Blue": "#1F4E5F", "Teal": "#1F7A78",
    "Peacock": "#0F6E7E", "Marine Blue": "#1C4E80", "Royal Blue": "#2749A6",
    "Cobalt": "#1F4FBF", "Sapphire": "#1E3F8F", "French Blue": "#3B6BB0",
    "Sky Blue": "#9CC4E4", "Baby Blue": "#B7D3EC", "Powder Blue": "#C4D6E8",
    "Ice Blue": "#D7E6F2", "Denim": "#3D5A80", "Slate Blue": "#5C6E91",
    "Turquoise": "#2AA8A8", "Aqua": "#5BC8C4", "Cerulean": "#2A7FBF",
    "Steel Blue": "#5E7F9E", "Air Force Blue": "#4A6D8C", "Periwinkle": "#8A94D6",
    # ---- reds / pinks / purples ----
    "Burgundy": "#5E1F2A", "Oxblood": "#4A1B22", "Wine": "#6B2436",
    "Maroon": "#5A2230", "Brick": "#8E3B2C", "Tomato Red": "#C6392B",
    "True Red": "#BE2633", "Crimson": "#A31D33", "Cherry": "#B01E36",
    "Raspberry": "#B02A5B", "Fuchsia": "#C42A84", "Magenta": "#C1268F",
    "Hot Pink": "#E9308F", "Bubblegum": "#F08BBE", "Pastel Pink": "#F4C7D4",
    "Blush": "#EBB8B4", "Rose": "#C97B84", "Dusty Rose": "#B98088",
    "Soft Rose": "#D8A3AB", "Watermelon": "#E45D6B",
    "Deep Plum": "#4B2440", "Plum": "#5E2B52", "Aubergine": "#43203C",
    "Eggplant": "#3C2140", "Mulberry": "#73305A", "Grape": "#5B3A8E",
    "Amethyst": "#7E4FA8", "Electric Purple": "#8A2BE2", "Violet": "#6E43B8",
    "Lavender": "#C4B4E0", "Lilac": "#CDB8E4", "Orchid": "#BA6BC4",
    # ---- brights / neons ----
    "Neon Yellow": "#EEFF2D", "Bright Yellow": "#FFD91E", "Lemon": "#F6E64B",
    "Bright Orange": "#FF7A1A", "Neon Orange": "#FF6A00", "Neon Pink": "#FF3EA5",
    "Electric Blue": "#1F6BFF", "Bright Cyan": "#19C8E6",
    # ---- soft cools ----
    "Soft Teal": "#5E938E", "Sea Glass": "#9FBFB6", "Misty Blue": "#A9BCCB",
    "Storm": "#6C7A86", "Blue Grey": "#7C8A99", "Heather": "#9C93A8",
    "Mauve": "#9A7B8C", "Soft Plum": "#7A5A72", "Cocoa Rose": "#A5847E",
    "Rosewood": "#7E4A4E", "Cadet": "#546A7B",
    # ---- metals ----
    "Gold": "#C9A24B", "Antique Gold": "#A8863C", "Brass": "#B5933F",
    "Bronze": "#8C6B32", "Copper Metal": "#B06A3B", "Rose Gold": "#C98F7A",
    "Silver": "#C7CBD1", "Bright Silver": "#D8DCE2", "Chrome": "#DDE2E8",
    "Gunmetal": "#5A5F66", "Pewter Metal": "#8B9097", "Platinum": "#D2D5D9",
    "Polished Steel": "#C9CFD8", "Matte Gold": "#B29450",
}


def n(*names):
    """Resolve colour names into (name, hex) pairs."""
    return [(x, C[x]) for x in names]


_METAL_SETS = {
    "warm": dict(
        yes=n("Gold", "Bronze", "Brass", "Antique Gold", "Copper Metal"),
        caution=n("Gunmetal", "Rose Gold"),
        no=n("Bright Silver", "Chrome", "Polished Steel"),
    ),
    "cool": dict(
        yes=n("Silver", "Platinum", "Gunmetal", "Pewter Metal"),
        caution=n("Rose Gold", "Matte Gold"),
        no=n("Brass", "Bronze", "Antique Gold"),
    ),
    "neutral_warm": dict(
        yes=n("Gold", "Antique Gold", "Bronze", "Rose Gold"),
        caution=n("Pewter Metal", "Gunmetal"),
        no=n("Bright Silver", "Chrome"),
    ),
    "neutral_cool": dict(
        yes=n("Silver", "Pewter Metal", "Platinum", "Rose Gold"),
        caution=n("Matte Gold", "Gunmetal"),
        no=n("Brass", "Bronze", "Copper Metal"),
    ),
}

SEASONS = {
    # ================= AUTUMNS =================
    "Deep Autumn": dict(
        family="Autumn", tagline="Rich · Warm · Deep",
        axes=dict(warm=78, depth=82, chroma=45, contrast=68),
        neutrals=n("Espresso", "Chocolate", "Dark Olive", "Navy", "Warm Taupe",
                   "Camel", "Stone", "Cream"),
        best=n("Navy", "Forest Green", "Olive", "Deep Teal", "Petrol Blue",
               "Rust", "Terracotta", "Burgundy", "Deep Plum", "Camel",
               "Chocolate", "Mustard", "Copper", "Dark Brown", "Warm Grey", "Moss"),
        avoid=n("Pastel Pink", "Lavender", "Baby Blue", "Cool Grey",
                "Silver Grey", "Pure White", "Neon Yellow", "Bright Lime",
                "Bright Orange", "Hot Pink", "Electric Purple", "Neon Green"),
        groups={
            "Neutrals": n("Espresso", "Chocolate", "Charcoal", "Warm Taupe", "Camel", "Cream"),
            "Blues": n("Navy", "Petrol Blue", "Deep Teal", "Marine Blue", "Denim", "Peacock"),
            "Greens": n("Forest Green", "Olive", "Moss", "Dark Olive", "Pine", "Spruce"),
            "Earth Tones": n("Rust", "Terracotta", "Cognac", "Caramel", "Khaki", "Bronze Brown"),
            "Reds": n("Burgundy", "Oxblood", "Brick", "Wine", "Maroon", "Tomato Red"),
            "Accents": n("Mustard", "Copper", "Deep Plum", "Amber", "Saffron", "Aubergine"),
        },
        metals=_METAL_SETS["warm"],
        tips_yes=["Tonal Dressing", "Rich Fabrics", "Matte Textures",
                  "Earth Colours", "Medium Contrast", "Leather Accessories"],
        tips_no=["Neon Colours", "Icy Pastels", "Stark White", "Fluorescent Colours"],
        suit_combos=[("Navy", "Cream", "Burgundy"),
                     ("Chocolate", "Cream", "Olive"),
                     ("Charcoal", "Ivory", "Rust"),
                     ("Forest Green", "Camel", "Chocolate")],
        casual=[("Olive", "Polo", "Navy", "Chinos"),
                ("Rust", "Sweater", "Dark Brown", "Jeans"),
                ("Camel", "Jacket", "Cream", "Tee"),
                ("Chocolate", "Shirt", "Khaki", "Pants")],
        glasses=[("Tortoise", C["Chocolate"]), ("Espresso", C["Espresso"]),
                 ("Antique Gold", C["Antique Gold"]), ("Dark Olive", C["Dark Olive"])],
        hair=[("Espresso Brown", C["Espresso"]), ("Dark Chestnut", C["Dark Brown"]),
              ("Warm Black", C["Soft Black"]), ("Auburn Lowlights", C["Cognac"])],
    ),
    "True Autumn": dict(
        family="Autumn", tagline="Golden · Warm · Earthy",
        axes=dict(warm=88, depth=60, chroma=50, contrast=48),
        neutrals=n("Chocolate", "Cognac", "Camel", "Khaki", "Warm Taupe",
                   "Stone", "Cream", "Dark Olive"),
        best=n("Rust", "Terracotta", "Burnt Orange", "Mustard", "Ochre",
               "Olive", "Moss", "Forest Green", "Deep Teal", "Camel",
               "Cognac", "Copper", "Brick", "Honey", "Khaki", "Pumpkin"),
        avoid=n("Pastel Pink", "Lavender", "Ice Blue", "Cool Grey",
                "Silver Grey", "Pure White", "Fuchsia", "Hot Pink",
                "Electric Purple", "Neon Yellow", "Bright Cyan", "Black"),
        groups={
            "Neutrals": n("Chocolate", "Cognac", "Camel", "Khaki", "Warm Taupe", "Cream"),
            "Blues": n("Deep Teal", "Petrol Blue", "Peacock", "Marine Blue", "Denim", "Teal"),
            "Greens": n("Olive", "Moss", "Forest Green", "Sage", "Dark Olive", "Grass Green"),
            "Earth Tones": n("Rust", "Terracotta", "Burnt Orange", "Caramel", "Sand", "Butterscotch"),
            "Reds": n("Brick", "Tomato Red", "Burgundy", "Maroon", "Rosewood", "Wine"),
            "Accents": n("Mustard", "Ochre", "Copper", "Amber", "Saffron", "Pumpkin"),
        },
        metals=_METAL_SETS["warm"],
        tips_yes=["Earth Colours", "Warm Layering", "Matte Textures",
                  "Suede & Leather", "Tonal Dressing", "Natural Fabrics"],
        tips_no=["Icy Pastels", "Stark White", "Cool Greys", "Neon Colours"],
        suit_combos=[("Chocolate", "Cream", "Olive"),
                     ("Olive", "Ivory", "Rust"),
                     ("Navy", "Ecru", "Mustard"),
                     ("Camel", "Cream", "Forest Green")],
        casual=[("Mustard", "Sweater", "Dark Olive", "Chinos"),
                ("Rust", "Henley", "Denim", "Jeans"),
                ("Olive", "Jacket", "Cream", "Tee"),
                ("Cognac", "Shirt", "Khaki", "Pants")],
        glasses=[("Amber Tortoise", C["Caramel"]), ("Cognac", C["Cognac"]),
                 ("Matte Gold", C["Matte Gold"]), ("Olive Horn", C["Olive"])],
        hair=[("Golden Brown", C["Cognac"]), ("Chestnut", C["Cocoa"]),
              ("Copper", C["Copper"]), ("Warm Caramel", C["Caramel"])],
    ),
    "Soft Autumn": dict(
        family="Autumn", tagline="Muted · Warm · Gentle",
        axes=dict(warm=64, depth=48, chroma=25, contrast=35),
        neutrals=n("Cocoa", "Warm Taupe", "Mushroom", "Greige", "Stone",
                   "Khaki", "Oyster", "Soft Charcoal"),
        best=n("Sage", "Moss", "Olive", "Soft Teal", "Sea Glass",
               "Dusty Rose", "Cocoa Rose", "Salmon", "Camel", "Butterscotch",
               "Terracotta", "Khaki", "Denim", "Mauve", "Warm Grey", "Rosewood"),
        avoid=n("Black", "Pure White", "Neon Pink", "Electric Blue",
                "Bright Yellow", "Neon Green", "Fuchsia", "Royal Blue",
                "Hot Pink", "Bright Orange", "Electric Purple", "True Red"),
        groups={
            "Neutrals": n("Cocoa", "Warm Taupe", "Mushroom", "Greige", "Stone", "Oyster"),
            "Blues": n("Denim", "Soft Teal", "Steel Blue", "Air Force Blue", "Misty Blue", "Cadet"),
            "Greens": n("Sage", "Moss", "Olive", "Soft Sage", "Sea Glass", "Khaki"),
            "Earth Tones": n("Camel", "Butterscotch", "Terracotta", "Sand", "Caramel", "Tan"),
            "Reds": n("Dusty Rose", "Cocoa Rose", "Rosewood", "Salmon", "Rose", "Brick"),
            "Accents": n("Mauve", "Soft Plum", "Honey", "Apricot", "Heather", "Jade"),
        },
        metals=_METAL_SETS["neutral_warm"],
        tips_yes=["Muted Tones", "Soft Textures", "Low Contrast",
                  "Blended Layers", "Brushed Fabrics", "Matte Finish"],
        tips_no=["High Contrast", "Neon Colours", "Stark Black & White", "Shiny Fabrics"],
        suit_combos=[("Soft Charcoal", "Oyster", "Rosewood"),
                     ("Cocoa", "Ecru", "Sage"),
                     ("Denim", "Cream", "Terracotta"),
                     ("Olive", "Stone", "Cocoa Rose")],
        casual=[("Sage", "Polo", "Warm Taupe", "Chinos"),
                ("Dusty Rose", "Sweater", "Denim", "Jeans"),
                ("Camel", "Jacket", "Oyster", "Tee"),
                ("Moss", "Shirt", "Stone", "Pants")],
        glasses=[("Light Tortoise", C["Tan"]), ("Warm Taupe", C["Warm Taupe"]),
                 ("Brushed Gold", C["Matte Gold"]), ("Rose Horn", C["Cocoa Rose"])],
        hair=[("Soft Brown", C["Cocoa"]), ("Dark Blonde", C["Butterscotch"]),
              ("Mushroom Brown", C["Mushroom"]), ("Warm Bronde", C["Tan"])],
    ),
    # ================= WINTERS =================
    "Deep Winter": dict(
        family="Winter", tagline="Deep · Cool · Intense",
        axes=dict(warm=28, depth=85, chroma=62, contrast=88),
        neutrals=n("Black", "Charcoal", "Midnight Navy", "Cool Grey",
                   "Pewter", "Pure White", "Ivory", "Espresso"),
        best=n("Black", "Midnight Navy", "Royal Blue", "Sapphire", "Emerald",
               "Pine", "True Red", "Crimson", "Burgundy", "Deep Plum",
               "Aubergine", "Fuchsia", "Raspberry", "Charcoal", "Pure White", "Teal"),
        avoid=n("Camel", "Mustard", "Rust", "Salmon", "Peach",
                "Khaki", "Warm Grey", "Butterscotch", "Cream", "Sage",
                "Apricot", "Honey"),
        groups={
            "Neutrals": n("Black", "Charcoal", "Midnight Navy", "Cool Grey", "Pure White", "Pewter"),
            "Blues": n("Royal Blue", "Sapphire", "Cobalt", "Marine Blue", "Slate Blue", "Cerulean"),
            "Greens": n("Emerald", "Pine", "Deep Forest", "Hunter Green", "Spruce", "Jade"),
            "Earth Tones": n("Espresso", "Oxblood", "Aubergine", "Eggplant", "Storm", "Gunmetal"),
            "Reds": n("True Red", "Crimson", "Cherry", "Burgundy", "Raspberry", "Wine"),
            "Accents": n("Fuchsia", "Magenta", "Deep Plum", "Violet", "Turquoise", "Ice Blue"),
        },
        metals=_METAL_SETS["cool"],
        tips_yes=["High Contrast", "Jewel Tones", "Crisp Lines",
                  "Sharp Tailoring", "Cool Palette", "Deep Anchors"],
        tips_no=["Earthy Warm Tones", "Muted Dusty Colours", "Beige Head-to-Toe", "Orange Tones"],
        suit_combos=[("Black", "Pure White", "True Red"),
                     ("Midnight Navy", "Pure White", "Burgundy"),
                     ("Charcoal", "Ice Blue", "Deep Plum"),
                     ("Navy", "Pure White", "Emerald")],
        casual=[("Emerald", "Sweater", "Black", "Jeans"),
                ("Royal Blue", "Polo", "Charcoal", "Chinos"),
                ("Black", "Jacket", "Pure White", "Tee"),
                ("Burgundy", "Shirt", "Midnight Navy", "Pants")],
        glasses=[("Black Acetate", C["Black"]), ("Gunmetal", C["Gunmetal"]),
                 ("Navy Horn", C["Midnight Navy"]), ("Silver", C["Silver"])],
        hair=[("Blue-Black", C["Black"]), ("Cool Espresso", C["Espresso"]),
              ("Dark Ash Brown", C["Soft Charcoal"]), ("Cool Brunette", C["Dark Brown"])],
    ),
    "Cool Winter": dict(
        family="Winter", tagline="Icy · Cool · Contrast",
        axes=dict(warm=15, depth=68, chroma=58, contrast=80),
        neutrals=n("Black", "Charcoal", "Navy", "Cool Grey", "Silver Grey",
                   "Pure White", "Ice Blue", "Pewter"),
        best=n("Royal Blue", "Cobalt", "Sapphire", "Emerald", "True Red",
               "Cherry", "Raspberry", "Fuchsia", "Magenta", "Deep Plum",
               "Grape", "Ice Blue", "Pure White", "Navy", "Charcoal", "Turquoise"),
        avoid=n("Rust", "Mustard", "Camel", "Terracotta", "Olive",
                "Khaki", "Warm Grey", "Cream", "Salmon", "Peach",
                "Cognac", "Bronze Brown"),
        groups={
            "Neutrals": n("Black", "Charcoal", "Navy", "Cool Grey", "Silver Grey", "Pure White"),
            "Blues": n("Royal Blue", "Cobalt", "Sapphire", "Cerulean", "Ice Blue", "Periwinkle"),
            "Greens": n("Emerald", "Pine", "Jade", "Spruce", "Turquoise", "Mint"),
            "Earth Tones": n("Pewter", "Storm", "Gunmetal", "Slate Blue", "Cadet", "Blue Grey"),
            "Reds": n("True Red", "Cherry", "Crimson", "Raspberry", "Wine", "Watermelon"),
            "Accents": n("Fuchsia", "Magenta", "Grape", "Violet", "Amethyst", "Deep Plum"),
        },
        metals=_METAL_SETS["cool"],
        tips_yes=["Cool Palette", "High Contrast", "Icy Accents",
                  "Crisp White", "Jewel Tones", "Sleek Finishes"],
        tips_no=["Warm Earth Tones", "Golden Yellows", "Orange Tones", "Muted Beiges"],
        suit_combos=[("Navy", "Pure White", "Cherry"),
                     ("Charcoal", "Ice Blue", "Deep Plum"),
                     ("Black", "Pure White", "Royal Blue"),
                     ("Midnight Navy", "Silver Grey", "Raspberry")],
        casual=[("Cobalt", "Sweater", "Charcoal", "Jeans"),
                ("Emerald", "Polo", "Navy", "Chinos"),
                ("Black", "Jacket", "Ice Blue", "Tee"),
                ("Raspberry", "Shirt", "Cool Grey", "Pants")],
        glasses=[("Black", C["Black"]), ("Crystal", C["Ice Blue"]),
                 ("Silver", C["Silver"]), ("Navy", C["Navy"])],
        hair=[("Cool Dark Brown", C["Dark Brown"]), ("Ash Brown", C["Soft Charcoal"]),
              ("Blue-Black", C["Black"]), ("Cool Silver", C["Silver"])],
    ),
    "Bright Winter": dict(
        family="Winter", tagline="Vivid · Cool · Electric",
        axes=dict(warm=32, depth=62, chroma=88, contrast=85),
        neutrals=n("Black", "Midnight Navy", "Charcoal", "Pure White",
                   "Ice Blue", "Cool Grey", "Pewter", "Navy"),
        best=n("Cobalt", "Electric Blue", "Royal Blue", "Emerald", "Kelly Green",
               "Turquoise", "True Red", "Cherry", "Fuchsia", "Hot Pink",
               "Magenta", "Violet", "Ice Blue", "Pure White", "Lemon", "Bright Cyan"),
        avoid=n("Khaki", "Mustard", "Rust", "Warm Grey", "Sage",
                "Dusty Rose", "Camel", "Mushroom", "Terracotta", "Olive",
                "Butterscotch", "Cocoa"),
        groups={
            "Neutrals": n("Black", "Midnight Navy", "Charcoal", "Pure White", "Ice Blue", "Cool Grey"),
            "Blues": n("Cobalt", "Electric Blue", "Royal Blue", "Cerulean", "Turquoise", "Bright Cyan"),
            "Greens": n("Emerald", "Kelly Green", "Jade", "Mint", "Grass Green", "Pine"),
            "Earth Tones": n("Charcoal", "Gunmetal", "Storm", "Pewter", "Slate Blue", "Navy"),
            "Reds": n("True Red", "Cherry", "Crimson", "Watermelon", "Raspberry", "Hot Pink"),
            "Accents": n("Fuchsia", "Magenta", "Violet", "Amethyst", "Lemon", "Periwinkle"),
        },
        metals=_METAL_SETS["cool"],
        tips_yes=["Saturated Colour", "High Contrast", "Colour Blocking",
                  "Crisp White", "One Vivid Accent", "Clean Lines"],
        tips_no=["Muted Dusty Tones", "Warm Earth Tones", "Faded Colours", "Beige Layers"],
        suit_combos=[("Navy", "Pure White", "True Red"),
                     ("Black", "Pure White", "Cobalt"),
                     ("Charcoal", "Ice Blue", "Fuchsia"),
                     ("Midnight Navy", "Pure White", "Emerald")],
        casual=[("Cobalt", "Polo", "Black", "Chinos"),
                ("Kelly Green", "Sweater", "Navy", "Jeans"),
                ("Pure White", "Tee", "Black", "Jacket"),
                ("True Red", "Shirt", "Charcoal", "Pants")],
        glasses=[("Black", C["Black"]), ("Crystal Clear", C["Porcelain"]),
                 ("Navy", C["Navy"]), ("Silver", C["Silver"])],
        hair=[("Glossy Black", C["Black"]), ("Cool Espresso", C["Espresso"]),
              ("Dark Cool Brown", C["Dark Brown"]), ("High-Shine Brunette", C["Soft Black"])],
    ),
    # ================= SPRINGS =================
    "Bright Spring": dict(
        family="Spring", tagline="Clear · Warm · Vivid",
        axes=dict(warm=68, depth=45, chroma=85, contrast=75),
        neutrals=n("Navy", "Chocolate", "Camel", "Ivory", "Warm Grey",
                   "Tan", "Charcoal", "Cream"),
        best=n("Coral", "Warm Coral", "Watermelon", "Tomato Red", "Turquoise",
               "Aqua", "Kelly Green", "Apple Green", "Cobalt", "Cerulean",
               "Golden Yellow", "Saffron", "Bright Orange", "Fuchsia", "Ivory", "Navy"),
        avoid=n("Black", "Cool Grey", "Dusty Rose", "Mauve", "Sage",
                "Mushroom", "Storm", "Oxblood", "Greige", "Soft Plum",
                "Heather", "Pewter"),
        groups={
            "Neutrals": n("Navy", "Chocolate", "Camel", "Ivory", "Warm Grey", "Tan"),
            "Blues": n("Cobalt", "Cerulean", "Turquoise", "Aqua", "French Blue", "Bright Cyan"),
            "Greens": n("Kelly Green", "Apple Green", "Emerald", "Grass Green", "Lime", "Jade"),
            "Earth Tones": n("Camel", "Caramel", "Honey", "Butterscotch", "Cognac", "Sand"),
            "Reds": n("Tomato Red", "Coral", "Watermelon", "True Red", "Warm Coral", "Cherry"),
            "Accents": n("Golden Yellow", "Saffron", "Bright Orange", "Fuchsia", "Apricot", "Violet"),
        },
        metals=_METAL_SETS["neutral_warm"],
        tips_yes=["Clear Colour", "Fresh Contrast", "One Bright Accent",
                  "Crisp Fabrics", "Warm Brights", "Light Layers"],
        tips_no=["Dusty Muted Tones", "Heavy Dark Layers", "Faded Colours", "All-Black Looks"],
        suit_combos=[("Navy", "Ivory", "Coral"),
                     ("Chocolate", "Cream", "Turquoise"),
                     ("Camel", "Ivory", "Tomato Red"),
                     ("Navy", "Pure White", "Golden Yellow")],
        casual=[("Coral", "Polo", "Navy", "Chinos"),
                ("Turquoise", "Tee", "Camel", "Shorts"),
                ("Kelly Green", "Sweater", "Denim", "Jeans"),
                ("Golden Yellow", "Shirt", "Chocolate", "Pants")],
        glasses=[("Honey Tortoise", C["Honey"]), ("Crystal", C["Porcelain"]),
                 ("Gold Wire", C["Gold"]), ("Navy", C["Navy"])],
        hair=[("Warm Brown", C["Cocoa"]), ("Golden Chestnut", C["Cognac"]),
              ("Copper Glints", C["Copper"]), ("Warm Black", C["Soft Black"])],
    ),
    "True Spring": dict(
        family="Spring", tagline="Sunny · Warm · Fresh",
        axes=dict(warm=85, depth=40, chroma=70, contrast=58),
        neutrals=n("Camel", "Tan", "Cognac", "Ivory", "Cream",
                   "Warm Grey", "Chocolate", "Khaki"),
        best=n("Coral", "Salmon", "Warm Coral", "Apricot", "Peach",
               "Golden Yellow", "Saffron", "Grass Green", "Apple Green", "Turquoise",
               "Aqua", "Cerulean", "Tomato Red", "Camel", "Ivory", "Honey"),
        avoid=n("Black", "Pure White", "Cool Grey", "Silver Grey", "Burgundy",
                "Deep Plum", "Mauve", "Storm", "Dusty Rose", "Pewter",
                "Oxblood", "Blue Grey"),
        groups={
            "Neutrals": n("Camel", "Tan", "Cognac", "Ivory", "Cream", "Warm Grey"),
            "Blues": n("Turquoise", "Aqua", "Cerulean", "French Blue", "Sky Blue", "Periwinkle"),
            "Greens": n("Grass Green", "Apple Green", "Kelly Green", "Lime", "Jade", "Moss"),
            "Earth Tones": n("Caramel", "Honey", "Butterscotch", "Sand", "Amber", "Cognac"),
            "Reds": n("Coral", "Salmon", "Warm Coral", "Tomato Red", "Watermelon", "Apricot"),
            "Accents": n("Golden Yellow", "Saffron", "Peach", "Bright Orange", "Lemon", "Emerald"),
        },
        metals=_METAL_SETS["warm"],
        tips_yes=["Warm Brights", "Golden Undertones", "Fresh Layers",
                  "Light Fabrics", "Sunny Accents", "Ivory over White"],
        tips_no=["Black Near Face", "Icy Pastels", "Cool Greys", "Heavy Dark Tones"],
        suit_combos=[("Camel", "Ivory", "Coral"),
                     ("Navy", "Cream", "Golden Yellow"),
                     ("Cognac", "Ivory", "Grass Green"),
                     ("Tan", "Cream", "Turquoise")],
        casual=[("Coral", "Polo", "Camel", "Chinos"),
                ("Aqua", "Tee", "Tan", "Shorts"),
                ("Golden Yellow", "Sweater", "Denim", "Jeans"),
                ("Apple Green", "Shirt", "Khaki", "Pants")],
        glasses=[("Amber Tortoise", C["Amber"]), ("Gold Wire", C["Gold"]),
                 ("Honey Crystal", C["Honey"]), ("Light Cognac", C["Caramel"])],
        hair=[("Golden Brown", C["Cognac"]), ("Warm Blonde", C["Butterscotch"]),
              ("Strawberry Glints", C["Copper"]), ("Light Chestnut", C["Caramel"])],
    ),
    "Light Spring": dict(
        family="Spring", tagline="Light · Warm · Delicate",
        axes=dict(warm=62, depth=22, chroma=55, contrast=35),
        neutrals=n("Ivory", "Cream", "Champagne", "Sand", "Tan",
                   "Warm Grey", "Camel", "Dove Grey"),
        best=n("Peach", "Apricot", "Salmon", "Warm Coral", "Mint",
               "Seafoam", "Aqua", "Sky Blue", "Periwinkle", "Lemon",
               "Butterscotch", "Sand", "Ivory", "Soft Rose", "Apple Green", "Camel"),
        avoid=n("Black", "Charcoal", "Burgundy", "Oxblood", "Deep Plum",
                "Espresso", "Navy", "Storm", "Gunmetal", "Brick",
                "Dark Olive", "Maroon"),
        groups={
            "Neutrals": n("Ivory", "Cream", "Champagne", "Sand", "Tan", "Dove Grey"),
            "Blues": n("Sky Blue", "Aqua", "Periwinkle", "Powder Blue", "Turquoise", "Cerulean"),
            "Greens": n("Mint", "Seafoam", "Apple Green", "Soft Sage", "Jade", "Grass Green"),
            "Earth Tones": n("Camel", "Butterscotch", "Honey", "Sand", "Apricot", "Tan"),
            "Reds": n("Peach", "Salmon", "Warm Coral", "Soft Rose", "Watermelon", "Coral"),
            "Accents": n("Lemon", "Golden Yellow", "Periwinkle", "Lilac", "Aqua", "Blush"),
        },
        metals=_METAL_SETS["neutral_warm"],
        tips_yes=["Light Layers", "Soft Warm Tones", "Low-Mid Contrast",
                  "Fresh Pastels", "Ivory Base", "Lightweight Fabrics"],
        tips_no=["Black Head-to-Toe", "Heavy Dark Tones", "Harsh Contrast", "Deep Jewel Tones"],
        suit_combos=[("Tan", "Ivory", "Warm Coral"),
                     ("Dove Grey", "Cream", "Sky Blue"),
                     ("Camel", "Ivory", "Seafoam"),
                     ("Sand", "Cream", "Apricot")],
        casual=[("Peach", "Polo", "Sand", "Chinos"),
                ("Mint", "Tee", "Tan", "Shorts"),
                ("Sky Blue", "Sweater", "Cream", "Pants"),
                ("Apricot", "Shirt", "Dove Grey", "Trousers")],
        glasses=[("Light Tortoise", C["Tan"]), ("Champagne Crystal", C["Champagne"]),
                 ("Gold Wire", C["Gold"]), ("Blush Horn", C["Blush"])],
        hair=[("Golden Blonde", C["Butterscotch"]), ("Light Warm Brown", C["Tan"]),
              ("Honey Highlights", C["Honey"]), ("Strawberry Blonde", C["Apricot"])],
    ),
    # ================= SUMMERS =================
    "Soft Summer": dict(
        family="Summer", tagline="Muted · Cool · Hazy",
        axes=dict(warm=38, depth=45, chroma=20, contrast=32),
        neutrals=n("Soft Charcoal", "Blue Grey", "Pewter", "Greige",
                   "Dove Grey", "Mushroom", "Porcelain", "Storm"),
        best=n("Slate Blue", "Steel Blue", "Misty Blue", "Soft Teal", "Sea Glass",
               "Sage", "Soft Sage", "Dusty Rose", "Mauve", "Soft Plum",
               "Heather", "Rose", "Denim", "Cadet", "Blue Grey", "Rosewood"),
        avoid=n("Bright Orange", "Neon Yellow", "Golden Yellow", "Rust",
                "Camel", "Pure White", "Black", "Tomato Red",
                "Kelly Green", "Cognac", "Saffron", "Hot Pink"),
        groups={
            "Neutrals": n("Soft Charcoal", "Blue Grey", "Pewter", "Greige", "Dove Grey", "Porcelain"),
            "Blues": n("Slate Blue", "Steel Blue", "Misty Blue", "Denim", "Cadet", "Air Force Blue"),
            "Greens": n("Sage", "Soft Sage", "Sea Glass", "Soft Teal", "Jade", "Spruce"),
            "Earth Tones": n("Mushroom", "Greige", "Taupe", "Storm", "Cocoa Rose", "Warm Grey"),
            "Reds": n("Dusty Rose", "Rose", "Rosewood", "Soft Rose", "Watermelon", "Raspberry"),
            "Accents": n("Mauve", "Soft Plum", "Heather", "Lavender", "Periwinkle", "Wine"),
        },
        metals=_METAL_SETS["neutral_cool"],
        tips_yes=["Muted Tones", "Low Contrast", "Soft Knits",
                  "Blended Layers", "Brushed Metals", "Tonal Greys"],
        tips_no=["Neon Colours", "Stark Black & White", "Warm Golden Tones", "High Shine"],
        suit_combos=[("Soft Charcoal", "Porcelain", "Dusty Rose"),
                     ("Blue Grey", "Dove Grey", "Soft Plum"),
                     ("Denim", "Porcelain", "Sage"),
                     ("Storm", "Misty Blue", "Rosewood")],
        casual=[("Sage", "Polo", "Blue Grey", "Chinos"),
                ("Dusty Rose", "Sweater", "Denim", "Jeans"),
                ("Slate Blue", "Tee", "Greige", "Pants"),
                ("Mauve", "Shirt", "Soft Charcoal", "Trousers")],
        glasses=[("Grey Tortoise", C["Pewter"]), ("Crystal Grey", C["Dove Grey"]),
                 ("Brushed Silver", C["Silver"]), ("Mauve Horn", C["Mauve"])],
        hair=[("Ash Brown", C["Taupe"]), ("Mushroom Brown", C["Mushroom"]),
              ("Cool Bronde", C["Greige"]), ("Smoky Blonde", C["Dove Grey"])],
    ),
    "Cool Summer": dict(
        family="Summer", tagline="Cool · Calm · Elegant",
        axes=dict(warm=20, depth=50, chroma=42, contrast=52),
        neutrals=n("Navy", "Slate Blue", "Cool Grey", "Silver Grey",
                   "Charcoal", "Porcelain", "Dove Grey", "Pewter"),
        best=n("French Blue", "Denim", "Sky Blue", "Periwinkle", "Slate Blue",
               "Raspberry", "Watermelon", "Rose", "Soft Plum", "Lavender",
               "Jade", "Spruce", "Navy", "Cool Grey", "Porcelain", "Amethyst"),
        avoid=n("Bright Orange", "Rust", "Mustard", "Camel", "Cognac",
                "Golden Yellow", "Olive", "Khaki", "Saffron", "Brick",
                "Butterscotch", "Bronze Brown"),
        groups={
            "Neutrals": n("Navy", "Slate Blue", "Cool Grey", "Silver Grey", "Charcoal", "Porcelain"),
            "Blues": n("French Blue", "Denim", "Sky Blue", "Periwinkle", "Cerulean", "Powder Blue"),
            "Greens": n("Jade", "Spruce", "Sea Glass", "Mint", "Soft Teal", "Emerald"),
            "Earth Tones": n("Pewter", "Storm", "Blue Grey", "Cadet", "Heather", "Taupe"),
            "Reds": n("Raspberry", "Watermelon", "Rose", "Crimson", "Wine", "Dusty Rose"),
            "Accents": n("Lavender", "Amethyst", "Soft Plum", "Orchid", "Periwinkle", "Fuchsia"),
        },
        metals=_METAL_SETS["cool"],
        tips_yes=["Cool Blues", "Rose Undertones", "Medium Contrast",
                  "Smooth Fabrics", "Grey Base", "Silver Details"],
        tips_no=["Warm Golden Tones", "Orange & Rust", "Olive Layers", "Brassy Metals"],
        suit_combos=[("Navy", "Porcelain", "Raspberry"),
                     ("Cool Grey", "Sky Blue", "Soft Plum"),
                     ("Charcoal", "Porcelain", "French Blue"),
                     ("Slate Blue", "Dove Grey", "Rose")],
        casual=[("French Blue", "Polo", "Cool Grey", "Chinos"),
                ("Raspberry", "Sweater", "Navy", "Jeans"),
                ("Sky Blue", "Tee", "Slate Blue", "Pants"),
                ("Lavender", "Shirt", "Charcoal", "Trousers")],
        glasses=[("Navy", C["Navy"]), ("Silver Wire", C["Silver"]),
                 ("Grey Crystal", C["Dove Grey"]), ("Plum Horn", C["Soft Plum"])],
        hair=[("Cool Brown", C["Dark Brown"]), ("Ash Brunette", C["Taupe"]),
              ("Cool Blonde", C["Dove Grey"]), ("Silver Grey", C["Silver"])],
    ),
    "Light Summer": dict(
        family="Summer", tagline="Airy · Cool · Light",
        axes=dict(warm=32, depth=20, chroma=40, contrast=30),
        neutrals=n("Dove Grey", "Silver Grey", "Porcelain", "Misty Blue",
                   "Greige", "Shell", "Powder Blue", "Cool Grey"),
        best=n("Sky Blue", "Powder Blue", "Periwinkle", "Misty Blue", "Mint",
               "Seafoam", "Lavender", "Lilac", "Pastel Pink", "Blush",
               "Soft Rose", "Watermelon", "Sea Glass", "Dove Grey", "Porcelain", "Aqua"),
        avoid=n("Black", "Espresso", "Rust", "Mustard", "Burgundy",
                "Dark Olive", "Brick", "Cognac", "Bright Orange", "Oxblood",
                "Deep Forest", "Chocolate"),
        groups={
            "Neutrals": n("Dove Grey", "Silver Grey", "Porcelain", "Greige", "Shell", "Misty Blue"),
            "Blues": n("Sky Blue", "Powder Blue", "Periwinkle", "Ice Blue", "Aqua", "Cerulean"),
            "Greens": n("Mint", "Seafoam", "Sea Glass", "Soft Sage", "Jade", "Soft Teal"),
            "Earth Tones": n("Greige", "Taupe", "Mushroom", "Blue Grey", "Heather", "Storm"),
            "Reds": n("Pastel Pink", "Blush", "Soft Rose", "Watermelon", "Rose", "Dusty Rose"),
            "Accents": n("Lavender", "Lilac", "Periwinkle", "Orchid", "Mauve", "Raspberry"),
        },
        metals=_METAL_SETS["cool"],
        tips_yes=["Light Layers", "Airy Pastels", "Low Contrast",
                  "Soft Blues", "Grey over Black", "Delicate Details"],
        tips_no=["Heavy Dark Tones", "Warm Earth Tones", "High Contrast", "Golden Metals"],
        suit_combos=[("Dove Grey", "Porcelain", "Sky Blue"),
                     ("Misty Blue", "Shell", "Soft Rose"),
                     ("Cool Grey", "Porcelain", "Lavender"),
                     ("Slate Blue", "Powder Blue", "Watermelon")],
        casual=[("Sky Blue", "Polo", "Dove Grey", "Chinos"),
                ("Mint", "Tee", "Greige", "Shorts"),
                ("Lavender", "Sweater", "Misty Blue", "Jeans"),
                ("Blush", "Shirt", "Silver Grey", "Pants")],
        glasses=[("Crystal", C["Porcelain"]), ("Light Grey", C["Dove Grey"]),
                 ("Silver Wire", C["Silver"]), ("Lilac Horn", C["Lilac"])],
        hair=[("Cool Blonde", C["Dove Grey"]), ("Light Ash Brown", C["Greige"]),
              ("Beige Blonde", C["Sand"]), ("Platinum Tones", C["Platinum"])],
    ),
}

SEASON_NAMES = list(SEASONS.keys())


def classify(warm: float, depth: float, chroma: float) -> str:
    """Map 0-100 axis scores to the nearest season by simple distance."""
    best_name, best_d = None, 1e9
    for name, s in SEASONS.items():
        a = s["axes"]
        d = (a["warm"] - warm) ** 2 + (a["depth"] - depth) ** 2 + (a["chroma"] - chroma) ** 2
        if d < best_d:
            best_name, best_d = name, d
    return best_name
